### PR TITLE
Added example .env file and tidied up README

### PR DESCRIPTION
**Pull request by harrymt**
#### Separated environment bariables into file
- Moved environment variables into separate file `.env`
- Read these environment variables using [`dotenv`](https://github.com/motdotla/dotenv)
- Added instructions to create a `.env` file from an example `.env.example` file

#### Tidied up README
- Added link for generating oAuth token
- Link js files when talking about them
- Separated installation/testing/development into sections

### CODE REVIEW

**Comment by harrymt** [comment]
@tailuge I have added a production check, so the `.env` file is only used during development and not in production / heroku

**Comment by tailuge** [comment]
Somehow I'm still bothered by the .env file hanging around :)  Is the motivation for this making it easier to run in Windows?

**Comment by harrymt** [comment]
@tailuge fair enough. 😄 The idea behind using a `.env` file is based on the [12 Factor App](https://www.12factor.net/).

The key benefits are:

- Cross platform
- Easy to change between deploys without changing any code

Downsides:
- Have to have a .env file hanging around
- Extra setup step instead of passing it into the script
- Have a higher potential to commit these files

**Comment by harrymt** [comment]
Removed all dotenv stuff, just tidied up README

**Pull request merged**
